language: node_js
node_js:
  - "8.2.1"

branches:
  only:
    - master

before_script:
  - cd frontend
  - npm i -g firebase-tools
  - npm i -g @angular/cli
  - npm run build
  - firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT
  